# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "MTC | Blog"

# Tagline next to the site title
tagline: "Master the Cloud, one article at a time."

# A description of your site for social meta tag, search engines, and feed.xml
description: "blog.masterthe.cloud | Let's master the Cloud. AWS, Azure, GCP. Masterthe.cloud "

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

# Sass
sass:
  sass_dir: _sass
  style: compressed

# The base hostname & protocol of your site for where absolute urls are needed
#url: "https://bloginn.netlify.app"
url: "http://blog.masterthe.cloud"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: Masterthe.Cloud
  url: http://masterthe.cloud/

# The shortname for your Disqus site to enable comments.
#disqus: "justgoodthemes"

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
#google_analytics: ""

# Author information - author info at the bottom of the post
author_name: "MTC | Blog"
author_bio: "Need to know the latest in CDK, or CodePipeline? Want to read up on how to enable Google Apps for business to serve as your Idp in your AWS SAML integration? This is the place for you!"
author_url:  "http://masterthe.cloud"
author_location: "Virginia Beach, Virginia"
author_image: /images/logoBlue.png

# Sidebar Add banner
#banner_url: "https://justgoodthemes.com"
#banner_image: images/banner.jpg
#banner_image_alt: "Alt text"

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
#mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
#twitter_url: "https://twitter.com/"
#facebook_url: "https://www.facebook.com/"
#github_url: "https://github.com/"
#codepen_url: "https://codepen.io/"
#dribbble_url: "https://dribbble.com/"
#medium_url: "https://medium.com/"
#instagram_url: "https://www.instagram.com/"
#pinterest_url: "https://www.pinterest.com/"
#linkedin_url: "https://www.linkedin.com/"
#weibo_url: "https://www.weibo.com/"

# http://jekyllrb.com/docs/pagination/
paginate: 4
paginate_path: '/blog/page:num/index.html'
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
